### ISSUE TITLE
dev : compatibility test #1 v1.5.4 from patch-1

### ISSUE THREAD

**Issue by anonymousfoxxo** [anonymousfoxxo/foxxo-netmon#8]
report results of compatibility test on v1.5.4 from patch-1

**Comment by anonymousfoxxo** [comment]
Windows 8.1 compatibility test complete

**Comment by sourabhwarrier** [comment]
Windows 11 compatibility test complete

**Comment by sourabhwarrier** [comment]
Windows 10 compatibility test complete
